---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: xorg, tags: ['xorg'] }
    - { role: lightdm, tags: ['lightdm'] }

  vars_prompt:
    - name: "pass"
      prompt: "User password"
