---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: xorg, tags: ['xorg'] }
    - { role: lightdm, tags: ['lightdm'] }
    - { role: set-keymap, tags: ['set-keymap'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: fonts, tags: ['fonts'] }

  vars_prompt:
    - name: "pass"
      prompt: "User password"
