---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: xorg, tags: ['xorg'] }
    - { role: images, tags: ['images'] }
    - { role: lightdm, tags: ['lightdm'] }
    - { role: set-keymap, tags: ['set-keymap'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: aws, tags: ['aws'] }
    - { role: clamav, tags: ['clamav'] }
    - { role: yubikey, tags: ['yubikey'] }

  vars_prompt:
    - name: "pass"
      prompt: "User password"
