---
- name: Install xorg-server
  pacman: name=xorg-server state=present

#- name: Install xorg-server-utils
#  pacman: name=xorg-server-utils state=present

- name: Install xorg-xinit
  pacman: name=xorg-xinit state=present

- name: Install xorg-twm
  pacman: name=xorg-twm state=present

- name: Install xorg-xclock
  pacman: name=xorg-xclock state=present

- name: Install xterm
  pacman: name=xterm state=present

- name: Install xorg-xrandr
  pacman: name=xorg-xrandr state=present

- name: Install xf86-video-nouveau
  pacman: name=xf86-video-nouveau state=present
  when: video_driver == "nvidia"

- name: Install lib32-mesa
  pacman: name=lib32-mesa state=present
  when: video_driver == "nvidia"

- name: Install virtualbox-guest-utils
  pacman: name=virtualbox-guest-utils
  when: "'virtualbox' in ansible_virtualization_type"

- name: Install linux-headers
  pacman: name=linux-headers
  when: "'virtualbox' in ansible_virtualization_type"
