---

- name: Install lightdm
  pacman: name=lightdm state=present

- name: Install lightdm-gtk-greeter
  pacman: name=lightdm-gtk-greeter state=present

- name: Enable lightdm
  service: name=lightdm enabled=yes

- name: Create lightdm-background directory
  file:
    path: /usr/share/pictures
    state: directory

- name: Copy lockscreen-image
  copy:
    src: /home/{{ user.name }}/Pictures/lockscreen
    dest: /usr/share/pictures

- name: Update config
  lineinfile:
    path: /etc/lightdm/lightdm-gtk-greeter.conf
    line: "{{ item }}"
  with_items: "{{ lightdm }}"

- name: Change theme, from archwiki
  lineinfile:
    path: /usr/share/xgreeters/lightdm-gtk-greeter.desktop
    regexp: "^Exec"
    line: "Exec=env GTK_THEME=Adwaita:dark lightdm-gtk-greeter"
