---
- name: Set hostname
  hostname: name={{ hostname }}
  when: hostname is defined

- name: Create group
  group: name={{ user.group }} state=present
  tags:
    - user

- name: Create user
  user: name={{ user.name }} groups={{ user.group }},wheel shell={{ user.shell }} password={{ pass|password_hash('sha512') }}
  tags:
    - user

- name: Install sudo
  pacman: name=sudo state=present
  tags:
    - sudo

- name: Add wheels to sudoers
  blockinfile:
    dest: /etc/sudoers
    block: "%wheel ALL=(ALL) ALL"

- name: Create AUR directory
  file: path=/home/{{ user.name }}/aur state=directory owner={{ user.name }} group={{ user.group }}
  tags:
    - packages
    - aur

- name: Install packages
  pacman: name={{ item }} state=present
  with_items: "{{ base_packages }}"
  when: item > 0
  tags:
    - packages

- name: Install software
  pacman: name={{ item }} state=present
  with_items: "{{ base_software }}"
  when: item > 0
  tags:
    - software

#AUR uses cower if present, otherwise cURL
- name: Install cower
  aur: name=cower user={{ user.name }} skip_pgp=yes
  tags:
    - packages
    - aur

- name: Install AUR packages
  aur: name={{ item }} user={{ user.name }}
  with_items: "{{ aur_packages }}"
  when: item > 0
  tags:
    - packages
    - aur
