---
- name: Set hostname
  hostname: name={{ hostname }}
  when: hostname is defined

- name: Install packages
  pacman: name={{ item }} state=present
  with_items: "{{ base_packages }}"
  tags:
    - packages

- name: Install AUR packages
  aur: name=cower user=root skip_pgp=yes
